In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set(
    palette=sns.color_palette("Paired"),
    color_codes=False,
    rc={
        "figure.figsize": (12, 8)
    }
)
from scipy.stats import linregress

plt.rcParams['figure.figsize'] = [12, 8]  # Bug; needed to be set twice

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('bert-base-nli-mean-tokens')

In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation

Using TensorFlow backend.


In [3]:
twitter_train=pd.read_csv('train_2kmZucJ.csv')
twitter_train

id  label                                              tweet
0        1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1        2      0  Finally a transparant silicon case ^^ Thanks t...
2        3      0  We love this! Would you go? #talk #makememorie...
3        4      0  I'm wired I know I'm George I was made that wa...
4        5      1  What amazing service! Apple won't even talk to...
...    ...    ...                                                ...
7915  7916      0  Live out loud #lol #liveoutloud #selfie #smile...
7916  7917      0  We would like to wish you an amazing day! Make...
7917  7918      0  Helping my lovely 90 year old neighbor with he...
7918  7919      0  Finally got my #smart #pocket #wifi stay conne...
7919  7920      0  Apple Barcelona!!! #Apple #Store #BCN #Barcelo...

[7920 rows x 3 columns]

In [4]:
num_frasi=7920

frasi=twitter_train['tweet'][0:num_frasi]
frasi.values
frasi_embeddings = np.array(model.encode(frasi.values))   
frasi_embeddings

array([[-0.20323323,  1.1629684 , -0.23558642, ...,  0.00179879,
         0.0439449 ,  0.16331212],
       [ 0.22049771,  1.0810663 ,  0.53353345, ...,  0.25489083,
         0.38358468,  0.09085761],
       [-0.14096376,  0.55092597,  0.8293394 , ...,  0.13509692,
        -0.3068057 ,  0.24172863],
       ...,
       [-0.55700916,  1.4130114 ,  0.22665161, ...,  0.62694734,
         0.10634047, -0.12266865],
       [-0.2651906 ,  0.34255734,  1.0838131 , ...,  0.03939691,
        -0.3335609 , -0.02337172],
       [-0.27246368,  0.84458476,  0.27600428, ..., -0.09396114,
        -0.46090028, -0.20908943]], dtype=float32)

In [5]:
shape_embed=frasi_embeddings[0].shape
shape_embed

(768,)

In [6]:
labels=np.array(twitter_train['label'][0:num_frasi])
labels

array([0, 0, 0, ..., 0, 0, 0])

In [7]:
model_keras = Sequential([
    Dense(512, input_shape=shape_embed),
    Activation('relu'),
    Dense(128),
    Activation('relu'),
    Dense(40),
    Activation('relu'),
    Dense(1),
    Activation('softmax'),
])

In [8]:
model_keras.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [9]:
model_keras.fit(frasi_embeddings,labels,epochs=50)

Epoch 1/50
7920/7920 [==============================] - 11s 1ms/step - loss: 11.4109 - accuracy: 0.2558
Epoch 2/50
7920/7920 [==============================] - 9s 1ms/step - loss: 11.4109 - accuracy: 0.2558
Epoch 3/50
7920/7920 [==============================] - 8s 1ms/step - loss: 11.4109 - accuracy: 0.2558
Epoch 4/50
7920/7920 [==============================] - 10s 1ms/step - loss: 11.4109 - accuracy: 0.2558
Epoch 5/50
7920/7920 [==============================] - 9s 1ms/step - loss: 11.4109 - accuracy: 0.2558
Epoch 6/50
7920/7920 [==============================] - 9s 1ms/step - loss: 11.4109 - accuracy: 0.2558
Epoch 7/50
7920/7920 [==============================] - 10s 1ms/step - loss: 11.4109 - accuracy: 0.2558
Epoch 8/50
7920/7920 [==============================] - 9s 1ms/step - loss: 11.4109 - accuracy: 0.2558
Epoch 9/50
7920/7920 [==============================] - 9s 1ms/step - loss: 11.4109 - accuracy: 0.2558
Epoch 10/50
7920/7920 [==============================] - 9s 1ms/step -

In [10]:
frase_test = np.array(model.encode(['I love iphone']))
frase_test
#frase_test[0]

predictions = model_keras.predict(frase_test)
predictions

array([[1.]], dtype=float32)

In [11]:
evaluates = model_keras.evaluate(frasi_embeddings,labels)
evaluates

7920/7920 [==============================] - 2s 241us/step


[11.348359947975236, 0.2558080852031708]